---
title: "Reading: Good coding practices"
output: 
  html_document: 
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the slides for this lesson we have already provided several additional resources, here are the most recommended:

## Highly recommended references

- Wilson, G; Bryan, J; et al. (2017) [Good enough practices in scientific computing.](https://doi.org/10.1371/journal.pcbi.1005510) PLoS Computational Biology 13(6): e1005510. https://doi.org/10.1371/journal.pcbi.1005510

 - Wilson, G; Aruliah, D.A; et al. (2014) [Best practices in scientific computing.](https://doi.org/10.1371/journal.pbio.1001745) PLoS Biology 12(1): e1001745. https://doi.org/10.1371/journal.pbio.1001745 (This is probably too advanced for this course, but is offered as reference)
 
- [The tidyverse style guide.](https://style.tidyverse.org/), by Hadley Wickham

## Other interesting resources:

- Benureau, F.C.Y; Rougier, N.P (2018)[Re-run, Repeat, Reproduce, Reuse, Replicate: Transforming Code into Scientific Contributions.](https://www.frontiersin.org/articles/10.3389/fninf.2017.00069/full) Frontiers in Neuroinformatics 11:69.    

- [Software Carpentry: Programming with R](https://swcarpentry.github.io/r-novice-inflammation/)

- [What They Forgot to Teach You About R](https://whattheyforgot.org/project-oriented-workflow.html), by Jennifer Bryan and Jim Hester
